classDiagram
  class e-cars-sentiments {
  }
  class executor {
  }
  class executor {
  }
  class feature_analysis {
  }
  class survey_creator {
  }
  class model {
  }
  class model_geneartioon {
  }
  class output {
  }
  class sentiment_plotter {
  }
  class survey_printer {
  }
  class prediction {
  }
  class ml_prediction {
  }
  class processor {
  }
  class feature_extractor {
  }
  class processor {
  }
  class sentiment_comparator {
  }
  class survey {
  }
  class fine_tune {
  }
  class data_loader {
  }
  class data_preprocessor {
  }
  class fine_tunning_workflow {
  }
  class generate_train_test {
  }
  class likert_survey_workflow {
  }
  class model_trainer {
  }
  class question_generator {
  }
  class summarizer {
  }
  class likert_test {
  }
  class question_generator {
  }
  class survery_generator {
  }
  class survey_analyser {
  }
  class survey_generation_transformer {
  }
  class t5_fine_tuner {
  }
  class t5_survery_generator {
  }
  class transformer_analyser {
  }
  class setup {
  }
  class utils {
  }
  class feature_selection {
  }
  class log_utils {
  }
  class utils {
  }
  e-cars-sentiments --> executor
