import logging
from transformers import T5Tokenizer, T5ForConditionalGeneration
from handler.feature_handler import FeatureHandler
from utils.log_utils import LoggerManager
from handler.category_handler import CategoryHandler


class QuestionGenerator:
    def __init__(self, category_handler, use_transformer=False, transformer_model="t5-small", log_level=logging.INFO):
        """
        Initializes the QuestionGenerator class.

        Args:
            category_handler: An instance of a class responsible for categorizing features.
            use_transformer (bool): If True, uses a transformer model for question generation.
            transformer_model (str): The name of the transformer model to use.
            log_level (int): Logging level for debugging.
        """
        self.category_handler = category_handler
        self.use_transformer = use_transformer
        self.logger = LoggerManager(log_level).get_logger(self.__class__.__name__)

        if use_transformer:
            self.logger.info("Initializing transformer model...")
            self.tokenizer = T5Tokenizer.from_pretrained(transformer_model)
            self.model = T5ForConditionalGeneration.from_pretrained(transformer_model)
            self.logger.info("Transformer model initialized.")

    def create_question_from_feature(self, feature):
        """
        Creates a survey question based on the given feature using either templates or a transformer model.

        Args:
            feature (str): A feature extracted from the data.

        Returns:
            str: A formatted survey question.
        """
        try:
            self.logger.info(f"Generating question for feature: {feature}")
            if self.use_transformer:
                return self._create_question_with_transformer(feature)
            else:
                return self._create_question_with_templates(feature)
        except Exception as e:
            self.logger.error(f"Error generating question for feature '{feature}': {e}")
            return f"Error generating question for feature '{feature}': {e}"

    def _create_question_with_templates(self, feature):
        """
        Creates a question using predefined templates.

        Args:
            feature (str): A feature extracted from the data.

        Returns:
            str: A question based on templates.
        """
        category = self.category_handler.categorize_feature(feature)

        templates = {
            'performance': [
                f"How satisfied are you with the {feature} performance of your electric car?",
                f"Do you believe the {feature} is a key factor in electric car performance?",
                f"How important is the {feature} when evaluating your electric car’s overall efficiency?"
            ],
            'design': [
                f"How would you rate the {feature} design of your electric car?",
                f"How important is the {feature} design in your decision to purchase this electric car?",
                f"Does the {feature} design enhance the electric car’s value for you?"
            ],
            'usability': [
                f"How easy is it to use the electric car with its {feature}?",
                f"How important is {feature} for improving the usability of the electric car?",
                f"Do you find the {feature} makes the electric car more user-friendly?"
            ],
            'affordability': [
                f"How would you rate the {feature} in terms of electric car affordability?",
                f"Do you think the {feature} offers good value for its price in an electric car?",
                f"How important is {feature} when considering the overall cost of your electric car?"
            ],
            'safety': [
                f"How would you rate the safety features related to {feature} in your electric car?",
                f"Do you feel the {feature} adds to the overall safety of your electric car?",
                f"How important is the {feature} for your feeling of safety in the electric car?"
            ],
            'general': [
                f"How important is the '{feature}' when considering purchasing an electric car?",
                f"How likely are you to choose an electric car that offers better '{feature}'?",
                f"To what extent does '{feature}' influence your decision when comparing electric cars?"
            ]
        }

        template_list = templates.get(category, templates['general'])
        return template_list[hash(feature) % len(template_list)]

    def _create_question_with_transformer(self, feature):
        """
        Creates a question dynamically using a transformer model.

        Args:
            feature (str): A feature extracted from the data.

        Returns:
            str: A question generated by the transformer model.
        """
        try:
            prompt = f"Generate a survey question about '{feature}' in the context of electric cars."
            self.logger.debug(f"Transformer prompt: {prompt}")

            input_ids = self.tokenizer.encode(prompt, return_tensors="pt")
            outputs = self.model.generate(
                input_ids,
                max_length=100,
                num_beams=5,
                temperature=0.7,
                no_repeat_ngram_size=2,
                early_stopping=True,
            )
            question = self.tokenizer.decode(outputs[0], skip_special_tokens=True)
            self.logger.info(f"Generated question: {question}")
            return question
        except Exception as e:
            self.logger.error(f"Error in transformer-based question generation: {e}")
            return f"Error generating question for feature '{feature}'"